/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPage;

import config.db_configuration;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author SCC-COMLAB
 */
public class addStock extends javax.swing.JInternalFrame {

    /**
     * Creates new form addStock
     */
    public addStock() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }
        public void reset(){
        id.setText("");
        no.setText("");
        date.setText("");
        itemno.setText("");
        itemname.setText("");
        quantity.setText("");
        buy.setText("");
        sell.setText("");
        total.setText("");
    }
    
    
    
    
        public void displayData(){
       
        try{
       
            db_configuration dbc = new db_configuration();
            ResultSet rs = dbc.getData("SELECT * FROM tbl_addstock");
            tbl_stock.setModel(DbUtils.resultSetToTableModel(rs));
       
        }catch(SQLException ex){
            System.out.println("Error Message: "+ex);
       
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_stock = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        itemno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        itemname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        buy = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sell = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        insert = new javax.swing.JButton();
        display = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        tbl_stock.setBackground(new java.awt.Color(0, 204, 204));
        tbl_stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_stockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_stock);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 70, 710, 100);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Item No.");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 300, 110, 30);

        itemno.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(itemno);
        itemno.setBounds(130, 300, 240, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Receiving Date:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 260, 110, 30);

        date.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(date);
        date.setBounds(130, 260, 240, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Receiving No.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 220, 110, 30);

        no.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(no);
        no.setBounds(130, 220, 240, 30);

        itemname.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(itemname);
        itemname.setBounds(130, 340, 240, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Item Name:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 340, 110, 30);

        quantity.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(quantity);
        quantity.setBounds(470, 180, 240, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quantity:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(380, 180, 90, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Buying Price:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(380, 220, 90, 30);

        buy.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(buy);
        buy.setBounds(470, 220, 240, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Selling Price:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(380, 260, 90, 30);

        sell.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(sell);
        sell.setBounds(470, 260, 240, 30);

        total.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(total);
        total.setBounds(470, 300, 240, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total Price:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(380, 300, 90, 30);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD STOCK");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 40));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 20, 150, 40);

        update.setBackground(new java.awt.Color(0, 204, 204));
        update.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update);
        update.setBounds(320, 390, 90, 30);

        insert.setBackground(new java.awt.Color(0, 204, 204));
        insert.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        insert.setText("INSERT");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        jPanel1.add(insert);
        insert.setBounds(220, 390, 90, 30);

        display.setBackground(new java.awt.Color(0, 204, 204));
        display.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        display.setText("DISPLAY");
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });
        jPanel1.add(display);
        display.setBounds(120, 390, 90, 30);

        delete.setBackground(new java.awt.Color(0, 204, 204));
        delete.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete);
        delete.setBounds(420, 390, 90, 30);

        clear.setBackground(new java.awt.Color(0, 204, 204));
        clear.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear);
        clear.setBounds(520, 390, 90, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 180, 110, 30);

        id.setEditable(false);
        id.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(id);
        id.setBounds(130, 180, 240, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        db_configuration dbc = new db_configuration();
        int num = dbc.updateData("UPDATE tbl_addstock "
                + "SET a_receivingno= '"+no.getText()+"', a_receivingdate='"+date.getText()+"', "
                        + "a_itemno='"+itemno.getText()+"', a_itemname='"+itemname.getText()+"', a_quantity='"+quantity.getText()+"', a_buyingprice='"+buy.getText()+"', a_sellingprice='"+sell.getText()+"', a_totalprice='"+total.getText()+"' "
                                + "WHERE a_id = '"+id.getText()+"'");
       
        if(num == 0){
           
        }else{
           JOptionPane.showMessageDialog(null, "Updated Successfully!");
           displayData();
           reset();
        }    
    }//GEN-LAST:event_updateActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        db_configuration dbc = new db_configuration();
        dbc.insertData("INSERT INTO tbl_addstock(a_receivingno, a_receivingdate, a_itemno, a_itemname, a_quantity, a_buyingprice, a_sellingprice, a_totalprice) "
                + "VALUES ('"+no.getText()+"', '"+date.getText()+"','"+itemno.getText()+"','"+itemname.getText()+"','"+quantity.getText()+"','"+buy.getText()+"','"+sell.getText()+"','"+total.getText()+"')");
        displayData();
        reset();
    }//GEN-LAST:event_insertActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        displayData();
    }//GEN-LAST:event_displayActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        
    }//GEN-LAST:event_deleteActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
           reset();
    }//GEN-LAST:event_clearActionPerformed

    private void tbl_stockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_stockMouseClicked
        int rowIndex = tbl_stock.getSelectedRow();
        if(rowIndex < 0){
            
        }else{
            TableModel model = tbl_stock.getModel();
            id.setText(""+model.getValueAt(rowIndex,0));
            no.setText(""+model.getValueAt(rowIndex,1));
            date.setText(""+model.getValueAt(rowIndex,2));
            itemno.setText(""+model.getValueAt(rowIndex,3));
            itemname.setText(""+model.getValueAt(rowIndex,4));
            quantity.setText(""+model.getValueAt(rowIndex,5));
            buy.setText(""+model.getValueAt(rowIndex,6));
            sell.setText(""+model.getValueAt(rowIndex,7));
            total.setText(""+model.getValueAt(rowIndex,8));
            

            
        }
    }//GEN-LAST:event_tbl_stockMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buy;
    private javax.swing.JButton clear;
    private javax.swing.JTextField date;
    private javax.swing.JButton delete;
    private javax.swing.JButton display;
    private javax.swing.JTextField id;
    private javax.swing.JButton insert;
    private javax.swing.JTextField itemname;
    private javax.swing.JTextField itemno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField no;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField sell;
    private javax.swing.JTable tbl_stock;
    private javax.swing.JTextField total;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
